### ISSUE TITLE
consider adding automatic cluster quality assessment with Greengard methods

### ISSUE THREAD

**Issue by nsteinme** [marius10p/KiloSort#5]
I.e. http://arxiv.org/abs/1508.06936

E.g. as a way to decide when to merge clusters.

**Comment by marius10p** [comment]
Actually, I had read that paper more carefully because I thought most of those tricks are quite weak. But then I saw that they admit themselves that most of their tricks shouldn't work well in practice, which was fair, the paper is more of a discussion than a clear benchmarking of methods. At the end, they arrive at "spike addition" as the most reliable method, and that's what we're doing already.

**Comment by nsteinme** [comment]
Ok! Sorry I didn't read it that closely. Sounds good.
